name: mecab_dart
description: Flutter plugin which provides binding to  Mecab library (Japanese Morphological Analyzer) on iOS and Android
version: 1.0.0
homepage:
  https://github.com/dttvn0010/mecab_dart

environment:
  sdk: '>=2.12.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.1
  wasm_ffi: ^1.0.2
  path_provider: ^2.0.11
  path: ^1.0.0
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.mecab_dart
        pluginClass: MecabDartPlugin
      ios:
        pluginClass: MecabDartPlugin
      windows:
        pluginClass: MecabDartPluginCApi
      linux:
        pluginClass: MecabDartPlugin
      macos:
        pluginClass: MecabDartPlugin
      web:

